### ISSUE TITLE
Tags "label", Names Cut off

### ISSUE THREAD

**Issue by BDansizen** [petereit/CheckinAir#10]
Love the app... However, when I use the app to check in, tags just print out as the word "Label" instead of the tag name, and on the parent/Pickup tag, the names get cut off if they are beyond 10 characters in length (often causing the last name to be missing)

**Comment by petereit** [comment]
I haven’t received any other reports of this issue. Please remove and reseat the spool of labels in your printer (sometimes they misread the label size and it throws off the auto-sizing.)

If reseating the label spool has no effect, please post a screen shot of your label configuration in Breeze as well as a photo of a printed label.

**Comment by BDansizen** [comment]
Its only on the parent tag. re-seating didn't seam to change anything. Attached is an image of a label and parent slip printed via the app and Brother QL-810W (right) and the same printed via the computer using the DYMO 450 Turbo(Left). No settings were changed. Note the tag name (1st Grade) and the name cut off on the parent pickup slip.
![img_5347a](https://user-images.githubusercontent.com/39273182/40059443-07b02014-5822-11e8-880e-bcff18a26419.jpg)
![img_5346](https://user-images.githubusercontent.com/39273182/40059455-10f59488-5822-11e8-82e3-9fcb4e7fe1e9.PNG)
![img_5342](https://user-images.githubusercontent.com/39273182/40059459-15d01fa0-5822-11e8-91da-c742538e970b.jpg)
![img_5343](https://user-images.githubusercontent.com/39273182/40059472-207dd3ca-5822-11e8-8e32-8065b1b99be2.jpg)

**Comment by petereit** [comment]
I believe these issues may be related to the issues some other users have reported. Please watch the app store for new version 1.33. If the newer version does not resolve the issues, please let me know.

**Comment by petereit** [comment]
Glad to hear it. Thank you for the feedback!

**Comment by petereit** [comment]
Sorry! I missed that setting when I was testing everyone’s tag setups last week. I’ll set up a label to match your setup this week and see if I can reproduce and fix that issue.

**Comment by petereit** [comment]
Resolved in release 1.36
