### ISSUE TITLE
Support for Dymo LabelWriter Printer?

### ISSUE THREAD

**Issue by brownbl1** [petereit/CheckinAir#11]
Hi Peter, thanks again for your work on this. Do you know of a way this could be made to work with the [Dymo LabelWriter Wireless](http://www.dymo.com/en-US/dymo%3Csup%3E%C2%AE%3C-sup%3E-labelwriter%3Csup%3E%C2%AE%3C-sup%3E-wireless-label-writer-wireless#tabContainer) printer? I know Brother printers support AirPrint which I think is critical to what is going on here, and I'm pretty sure the Dymo printers do not, but thought I'd double check with you in case you were aware of a hack/workaround.

**Comment by petereit** [comment]
No, sorry. This app was designed exclusively for AirPrint-enabled label printers.
