### ISSUE TITLE
Text not Printing

### ISSUE THREAD

**Issue by jpopelcc** [petereit/CheckinAir#13]
Great App!  Need a little help though.  For the child tag, I selected "Text" for the upper left tag position.  I typed in the short title of the class "KidZone" without the quotes.  It will not print on the tags.  However, it prints fine on the USB Dymo Label Printers.  I used the same option for the parent tags and it also is not printing.  Other options, such as Name, Date, 3-digit number, etc all print correctly.

One last thing - just like another user who posted, long names on the parent tags are cut short.

Thank you

**Comment by jpopelcc** [comment]
Attached screen capture of name tag and parent tag - my problem fields are where it says "KidZone" - those are using the text option.  Child Name, Date, etc work OK. 

<img width="738" alt="screen shot 2018-05-25 at 11 22 36 am" src="https://user-images.githubusercontent.com/39504523/40560197-1f28e4e4-600e-11e8-804c-a06ed4e36e4a.png">
<img width="734" alt="screen shot 2018-05-25 at 11 22 51 am" src="https://user-images.githubusercontent.com/39504523/40560198-1f470762-600e-11e8-8dc8-fadeef24fa2a.png">

**Comment by petereit** [comment]
These issues have been resolved. Please watch the app store for new version 1.33.
