### ISSUE TITLE
customized text tags not printing

### ISSUE THREAD

**Issue by lcartmell** [petereit/CheckinAir#14]
Love the idea.. when I use the app to check in, tags just print out as the word "Label" instead of the text, tag name, date or any other detail that is specified to print.

**Comment by petereit** [comment]
Thanks for the report. Could you please post a screen shot of your label setup? I want to make sure I have my label set up identically to yours for testing.

**Comment by lcartmell** [comment]
Yes.. this is the label set up that I have. Is this what you were looking for?

**Comment by petereit** [comment]
Yes. The screen where it shows what you have configured for each field on the label.

**Comment by petereit** [comment]
This appears to be related to similar issues already reported. They should be resolved with the next update release. Please watch the app store for new version 1.33.
