### ISSUE TITLE
newest update

### ISSUE THREAD

**Issue by lcartmell** [petereit/CheckinAir#15]
Thank you so much for updating the app... I have one other concern/question. When I go to print the tags, it is not recognizing the printer. Is there something I change to recognize the printer? And do you recommend using the brother QL-810W wireless printer or the DYMO wireless printer? 

Thank you!

**Comment by petereit** [comment]
My app only recognizes AirPrint-capable label printers, so only the Brother label printer will work with it.

**Comment by lcartmell** [comment]
okay great! thank you!
