### ISSUE TITLE
Printing additional name tag

### ISSUE THREAD

**Issue by sp20uth** [petereit/CheckinAir#19]
The app doesn't seem to print the 3rd name tag. The first 2 name tags print normally but if we want to Print Additional Name Tag it isn't printing. It seems as if it is an issue with the app not with Breeze specifically. Any thoughts. Great app by the way we love it and works great for our church and others.

**Comment by petereit** [comment]
Sorry, that’s a me-thing. I made a lot of programming assumptions based on how my church uses Breeze. 

Can you post a screenshot of where you have it configured to print an additional tag? I’d like to set up a test event in my church’s system that matches your setup so I can determine what needs to be modified in my app.

**Comment by sp20uth** [comment]
Here is a screenshot of editing the event details to print an additional nametag.
![screen shot 2018-08-09 at 11 57 27 am](https://user-images.githubusercontent.com/42227246/43913731-758c935a-9bcb-11e8-9b29-c39d418525a6.png)

**Comment by petereit** [comment]
I have corrected this issue. CheckinAir version 1.34 has been submitted to the Apple Store for review. I will notify you once Apple has released it for download. Once you have updated your CheckinAir app to this new version, please let me know if it resolves the issue for you.

**Comment by sp20uth** [comment]
Thank you very much. 

Steve Peoples

**Comment by petereit** [comment]
The new version has been approved and should now be available to update inbthe App Store.
