### ISSUE TITLE
Which Printer and Which Labels?

### ISSUE THREAD

**Issue by sacoward** [petereit/CheckinAir#20]
We are looking at using CheckinAir for one of our campuses.  

Are there any recommended Brother printers?  Is Brother QL-810W the cheapest option?  Or does someone know of a cheaper one?

The other question (and more important) is what labels do you use?  
Thanks!

**Comment by petereit** [comment]
If you can find a used Brother QL-710W in good condition it will work as well. They’re discontinued, but we use 3 of them and they work fine. 

As far as I know, though, Brother is the only label printer manufacturer that supports Apple AirPrint. 

The labels that we use with the printer are LD Compatible Broker DK-2205 Rolls of White Label Tape / 2.4 in. x 100 ft. We have found the labels online from various companies, including Amazon.  Sometimes Amazon is cheaper but other companies online have offered better pricing at times.

**Comment by sacoward** [comment]
Thanks!  Is there any issue with the continuous roll of labels and parent tags?  Or does it automatically cut between the kid tag and parent tag?

**Comment by petereit** [comment]
Auto-cuts between tags. 👍🏼
