### ISSUE TITLE
Working Xcode Project

### ISSUE THREAD

**Issue by Martinaude** [petereit/CheckinAir#22]
Hey Mark!

What a great app you have created! Thanks for this. it is a great help and we looking at implementing it in our current check check in area. I would like to know if it would be possible to get a full working Xcode project to customise for our church? We would like to brand it and fine tune the layout to seamlessly integrate with our current apps. The current build has missing files, and can therefore not compile. We seem to be missing UIKitCategories.h & UIKitCategories.m, Launchscreen.storyboard, a few icons, and SVProgressHUD folder with contents. 

Is this a possibility or not? Thanks so much! and great job again!

**Comment by petereit** [comment]
Thanks for the feedback! I definitely need to figure out how to properly do pulls/commits to/from Github. 

Email me directly (MarkPetereit at iCloud dot com.) I’ll zip and email you my local project files.

Mark

**Comment by petereit** [comment]
I completely rebuilt the GitHub repository from my local repository. Try pulling it now and see if it works for you.

**Comment by petereit** [comment]
Hey, Martinaude, just wanted to give you a heads-up. Breeze is working on v3 of their checkin web front-end. It has different print code and will not work with the current code base of my CheckinAir app. However, they were nice enough to give me the URL to a working prototype version and I was able to implement new code that will allow it to work with both v2 and v3 of their page.

When they get within a week of rolling out v3 they're going to let me know. I'll have the code in this repository already updated and ready to go. Watch for the v1.50 release and make sure you pull the updated code into your project.
