### ISSUE TITLE
Additional Name tag not printing correctly

### ISSUE THREAD

**Issue by sp20uth** [petereit/CheckinAir#26]
We are experiencing a couple very specific problems with the app. 

1. Isn’t checking people out when using 2 different ipads. 

2. Specific label information isn’t printing, such as when customizing the label if you select tag name it prints “label” in that field. 

3. Another problem we are experiencing is the tag specific labels don’t print correctly depending on the options selected.

4. When the additional name tag is selected as in the scenario below it prints 3 tags for all tags not just the one that is selected. 
 We have 2 ipads running this scenario and the 1 running version 1.32 works correctly and the one running version 1.35 doesn't. So the app that's been updated doesn't handle this correctly

![customize name tag](https://user-images.githubusercontent.com/42227246/45786802-d22a2280-bc37-11e8-8927-1883e547c53a.png)
![name tag options](https://user-images.githubusercontent.com/42227246/45786803-d22a2280-bc37-11e8-81d0-7bc1ce79e044.png)

**Comment by petereit** [comment]
Thank you for the information. I’ll look into the issues and see if I can get an update pushed this weekend. 

Mark

**Comment by petereit** [comment]
I believe I have the "tag name prints Label" issue and the "print additional Name" issues resolved. I'm pushing a new version now. I'll let you know when Apple approves it and releases it to the App Store.

**Comment by petereit** [comment]
Version 1.36 is now available in the App Store. Please update one of your iPads to this new version, test your issues and let me know.

**Comment by petereit** [comment]
I identified the issue with the additional name tag printing. Please update to version 1.37 when it hits the app store.
