### ISSUE TITLE
Getting Kicked out of App When Printing Check-in Labels

### ISSUE THREAD

**Issue by Mtdkennedy** [petereit/CheckinAir#27]
When checking a child into the system, the badge is set up to prompt for information (we enter pager number in this prompted field).  After being prompted and typing in the information, the app is kicking us out of it without an error message.  If I remove the prompted field in the badge, the app does not kick us out.

Do you have any suggestions for us to try?

Thanks

**Comment by petereit** [comment]
I’m sorry about that. It’s not a feature we use at my church. I’ll have to set up some test labels in my system this week to determine what’s causing the issue. 

Mark

**Comment by petereit** [comment]
I have identified the issue that's causing the app to abort when a Prompt is included in the tag. Please watch the App Store for the v1.37 update.
