### ISSUE TITLE
Offline capability

### ISSUE THREAD

**Issue by skromann2010** [petereit/CheckinAir#28]
Due to major network issues having the ability to use the app offline and then sync the data would be super helpful. Is there a way to do this? Or be able to use the printers WiFi wlan or blue tooth functions to print instead of needing to be on the network. Any help is appreciated.

**Comment by petereit** [comment]
No, I'm sorry, that's not possible. Breeze is an online web service. At it's core, all my app is is a web browser that intelligently hijacks Breeze's print subroutines and converts them to AirPrint-friendly commands. Without being connected to the internet, my app can't do anything.

**Comment by skromann2010** [comment]
Thank you for the quick response. And that would work just fine if I could get the printer to do a direct connect via wlan or Bluetooth. Is that possible?


Sent from Yahoo Mail for iPhone


On Tuesday, October 9, 2018, 3:30 AM, Mark Petereit <notifications@github.com> wrote:


No, I'm sorry, that's not possible. Breeze is an online web service. At it's core, all my app is is a web browser that intelligently hijacks Breeze's print subroutines and converts them to AirPrint-friendly commands. Without being connected to the internet, my app can't do anything.

**Comment by petereit** [comment]
Unfortunately, a WiFi connection is a requirement of Apple’s AirPrint protocol. The iPad/iPhone must be connected to the same WiFi network as the AirPrint-capable label printer.
