### ISSUE TITLE
Connecting Brother printer to Checkin Air

### ISSUE THREAD

**Issue by SherryJoyTaylor** [petereit/CheckinAir#3]
When I am attempting to check in using Checkin Air, I am unable to connect to my printer. I then test my connection and am unable to connect. It says I need to connect to DYMO Plugin. What should I do to connect from here?

Thank you!

![img_1324](https://cloud.githubusercontent.com/assets/25514912/22566583/6a91f01e-e941-11e6-87c2-b0783b9d29f5.png)

**Comment by petereit** [comment]
I'm not familiar with the screen you're displaying. How did you navigate to it?

**Comment by SherryJoyTaylor** [comment]
Events, Check In, Select a child to check in, No AirPrint Printers Found, back to Dashboard, More, Help, Test Printer Connection (under check in), then the connection fails. I then use Safari and follow the same process which leads me to the screen I posted.

Hope this makes sense. Thank you for responding so quickly.

**Comment by petereit** [comment]
If you're seeing the message “No AirPrint Printers Found” it means your Brother QL-710W label printer isn't configured properly or connected to the same wireless network as your iPad. 

Mark

**Comment by SherryJoyTaylor** [comment]
Thank you so much! This helps me a lot.

 

Sherry
