### ISSUE TITLE
some labels not printing

### ISSUE THREAD

**Issue by jfcg5328** [petereit/CheckinAir#30]
Hi!  We are glad to be using CheckinAir!  We have been using it for just under 2 months.  Our issue is that there are several children whose stickers won't print for nursery.  For clarity, we'll call one of them Matthew. 

- Matthew's parents check Matthew in, he looks checked in, but a sticker never prints. 
-  Matthew's sibling's stickers print, but his won't.  If we try and do family printing, including Matthew, then no one in the family will print. 
- Joshua's family can walk up, their sticker prints,  then Matthew's family walks up, doesn't print.  Then Dan's family walks up.  Dan's prints.  Still no Matthew sticker. 

- It is consistently the same 4-5 kids (all who happen to be 2 year old boys) who do not print. 

- We are using one printer and one iPad (sorry not sure what iOS it's running)
- Is is consistent if using a phone or the iPad. 
- when we were in the test phase, I was able to print these boys' stickers, but then something happened (that's where we're confused as to what) and we no longer can print them! 

Thanks for any help or insight!  Very much appreciate it! 
Julia

**Comment by petereit** [comment]
My app doesn’t determine who gets printed and who doesn’t. It just goes by the information that Breeze provides. (Though I’m not sure if my app handles the Print Family function correctly. We don’t use that at my church and I haven’t tested it.)

Since the boys are all in the same age group, I would double check your event settings in Breeze to ensure that group has not been excluded from printing.

**Comment by petereit** [comment]
Sorry for letting this issue stay open so long. Did you find a solution?

**Comment by jfcg5328** [comment]
Hi Mark,

We thought we did, but now we're having trouble again.  It seemed to be a
random glitch-- where if something was or wasn't in the allergies field
(which we had printing in the left hand corner) it was causing it not to
print.

I hooked up a dymo printer to a computer and using Breeze realized that on
the children not printing with Check-In Air the word "label" was was
printing in the left hand corner where allergies should be printing.
Another team member went through and changed the field within Breeze-- and
to be honest, I'm not sure if he took allergies out or made n/a an option
or what.

It worked for a couple weeks, and now some new kiddos won't print! So now
I'm wondering what my next steps should be to find a solution.  I may try
taking off the allergy option all together this week and see if that
changes anything.

Thanks for reaching out!  If you have any other ideas... I'd love to hear
them!

Julia Clemens

**Comment by petereit** [comment]
Ah! The word “label” printing is a known glitch in my app. I have fixed it, but I need to push an updated version to the Apple App Store. (Thanks for the reminder!)

Mark

**Comment by petereit** [comment]
I just pushed a new version, v1.4, of my CheckinAir app to the app store. It should correct the issue with family checkin, and should resolve your missing labels issue.

Please update to v1.4 and let me know if your labels are produced correctly.

**Comment by petereit** [comment]
Now that Breeze has released their own official AirPrint-supporting app, I am closing down support for my version.
