### ISSUE TITLE
Checkin air not syncing with Breeze?

### ISSUE THREAD

**Issue by Perkybunch1** [petereit/CheckinAir#32]
Hi, I am trying to locate the event I set up on Breeze, but the Checkin Air doesn't display the event.  I am using an iPad and Brother printer.  Thanks, Warren

**Comment by petereit** [comment]
Can you locate it if you log into Breeze in a regular web browser?

Mark

**Comment by Perkybunch1** [comment]
Yes, I logged into Breeze using a pc and was able to locate the event.  I tried multiple times and cycled the iPad off and on as I am having difficulty getting this to work consistently.  My brother (who is in IT) helped me out last time and adjusted the church’s network settings.  We have two iPads, I wonder whether that makes a difference, maybe when he fixed it last time, it was the other iPad?

I really appreciate any guidance you can provide.

Thanks,

Warren

**Comment by petereit** [comment]
At its root, all my app is is a basic web browser with a routine that “hijacks” Breeze’s print routine.

Launch Safari on the iPad in question and log into Breeze. If you can see your scheduled event there, you should see it in my app. 

If you can’t log in using Safari on that iPad, then you have some other issues outside of my app. 

Mark

**Comment by Perkybunch1** [comment]
I logged into Breeze using my iPad and saw the scheduled event, then I
logged into Checkin Air on my iPad and was able to see the scheduled
event.  I will go back to the church at some point and try again.  If it
doesn't work, I will throw in the towel, as I don't have the skills to to
get Breeze to work consistently.  I do appreciate your assistance on this.

Thank you.

Warren

**Comment by petereit** [comment]
It’s just a web site. If it works in one place but doesn’t in another, it’s a network issue. 

Mark

**Comment by petereit** [comment]
Were you able to resolve this? I'd like to close this issue.

Also, if you haven't already, please update your CheckinAir app to v1.4. Breeze updated their checkin page and v1.4 of my app is required to continue functioning correctly.

**Comment by Perkybunch1** [comment]
Oh, sorry, I didn’t realize it was still open.  Yes, the issue is resolved.  I did run into another problem, not realizing I had to “use the old check in system”.  Thanks for all your work on the app!

Warren

**Comment by Perkybunch1** [comment]
Mark,  

FYI, per the Breeze Rep: The new app rolling out will be very similar to (and replacing) the current third-party app, allowing for easier wireless printing with airprint-compatible printers.

**Comment by petereit** [comment]
Yep. I’m aware of it. 

Mark
