### ISSUE TITLE
Check in Air doesn't find Brother printer

### ISSUE THREAD

**Issue by Liz76** [petereit/CheckinAir#34]
Hi, I am new to the Breeze/Checkin Air system.  I'm trying to iron out the issues before we implement on Sundays.  We have an iPad, a Brother QL-810W printer, the Check in Air app, and a Breeze account.  I've verified that the iPad and printer are on the same wifi network.  When I checkin a child on the app, no printer is found.  I read in another thread that once you print the first label, the app will then "see" the printer for all the other labels.  But I don't know how to print the first label.  Any help is much appreciated!!

**Comment by petereit** [comment]
On the first Checkin, the AirPrint dialogue will pop up, you select your label printer and out pops the label. 

Every Checkin from then on will just go straight to the printer – no pop up. 

The Breeze system doesn’t know anything about AirPrint printers, so if you try their “Check Printer” function it won’t see your AirPrint printer. 

Mark

**Comment by Liz76** [comment]
The AirPrint dialogue never did pop up.  Is there a way to make it pop up?

**Comment by petereit** [comment]
It should as soon as you check someone in. Are you using family checkin? Because I do have an issue with that that I’m working to resolve. 

Mark

**Comment by cbc-tech** [comment]
This app has been awesome and we have been using it for months. Now that Breeze just updated their Checkin to v2, it is no longer finding the Brother Printer. I can go into a browser, see the printer & print no problem, but no longer from the app.

**Comment by petereit** [comment]
What happens when you check someone in. Do you see the AirPrint dialog?

Mark

**Comment by cbc-tech** [comment]
It says it can't find the printer. Click the Fix Printer button and that printing has been temporarily disabled for this event.

When I click, Fix the Printer, it goes through Breeze's stuff like I am using a Dymo printer, which is no help.

**Comment by petereit** [comment]
That’s odd. You’re logging in through my CheckinAir app?

Mark

**Comment by dapoop84** [comment]
We too are having this same issue. It looks like Breeze pushed the new Check In update live. I am not sure what the CheckinAir app uses to route to the Brother printers, but the default URL has now changed.

Example of old URL - churchname.breezechms.com/checkin
New URL - churchname.breezechms.com/checkin/v3

They added the v3 to route to the new interface. This may be what is causing the disconnect. I have been looking into how to change back to the old check in page, but have been unsuccessful so far.

Thanks,
David

**Comment by petereit** [comment]
OK, hang tight everyone. I’m going to push a new update by Friday that should resolve this. 

Mark

**Comment by ianandtj** [comment]
Thank you! I just read this, so you can disregard Issue #35 I just entered as I'm having the same issue as described above using the App with Breeze's new check-in process.

**Comment by Robc001** [comment]
Here at our Church we have been using the PC based Breeze and we just purchased 5 iPads and Brother QL-810W printers so I hope Mark gets us up and running..
Thank you Mark !!!!

**Comment by petereit** [comment]
No worries! I’ll have you up and running again soon. (Or I’m going to have MY nursery coordinator to answer to!) 😱😱😱

Mark

**Comment by petereit** [comment]
I'm uploading v1.4 image to the Apple App Store now. This should get everyone operational again.

**Comment by ianandtj** [comment]
Did version 1.4 get uploaded? I still only see version 1.37 in the App Store version history?

- sent from my iPhone

________________________________

**Comment by petereit** [comment]
It has to go through Apple’s App Store review process before its updated in the App Store. I have received confirmation that it has been approved, so v1.4 should be available now. 

Mark

**Comment by petereit** [comment]
v1.4 is officially available. I recommend everyone update to this version immediately. It should get you operational for your Sunday services.
