### ISSUE TITLE
New Breeze Interface Support

### ISSUE THREAD

**Issue by triegler** [petereit/CheckinAir#36]
Hi Mark!

We are absolutely loving CheckinAir! With Breeze moving to the new interface by default, is there an ETA on when CheckinAir will work with it? It's not a rush, we continue to use the original interface, and as long as Breeze doesn't turn that off, we're good =) Thank you for your work on this! If there is anything I can to do help, please let me know!

~Tim
Rush Creek Bible Church

**Comment by triegler** [comment]
Just saw issue #34. Closing this one. Thank you!

**Comment by petereit** [comment]
Go ahead and migrate to this one:

Breeze Check In by Breeze LLC
https://itunes.apple.com/us/app/breeze-check-in/id1451544075?mt=8

Mark
