### ISSUE TITLE
Calendar options

### ISSUE THREAD

**Issue by poplutheranchurch** [petereit/CheckinAir#6]
Hello. When I log into CheckinAir and try to choose a calendar date it is not loading.

**Comment by petereit** [comment]
Thank you for the report. I have confirmed on my end and I'm investigating.

On Aug 29, 2017, at 12:02 PM, poplutheranchurch <notifications@github.com> wrote:

Hello. When I log into CheckinAir and try to choose a calendar date it is not loading.

**Comment by petereit** [comment]
It appears to be an issue with the Breeze web site itself. I have confirmed that the calendar dropdown does not work when I pull up our Breeze checkin site in Safari on my iPad. It also does not work from the browser on my PC.

I will contact Breeze and log a support issue.

**Comment by poplutheranchurch** [comment]
Thank you so much!!

Blessings!
Tiffany

Sent from my iPhone

On Aug 29, 2017, at 3:49 PM, Mark Petereit <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears to be an issue with the Breeze web site itself. I have confirmed that the calendar dropdown does not work when I pull up our Breeze checkin site in Safari on my iPad. It also does not work from the browser on my PC.

I will contact Breeze and log a support issue.

**Comment by poplutheranchurch** [comment]
Greetings,

I am wondering if this issue was resolved?

Faithfully Yours,
Tiffany

**Comment by petereit** [comment]
Yes. I received a notification from Breeze support at 8/31 at 12:18pm that they pushed an update to their web service to resolve the issue.
